### PR TITLE
Add GUI support for VHDs

### PR DESCRIPTION
**Pull request by sards3**
This PR adds initial GUI support for VHDs. Selecting existing VHDs and creating new VHDs are supported. Fixed, dynamic, and diff types are supported. 

Known issues:
When creating a new diff VHD, the parent's geometry/size is used, and the HD creation dialog's geometry/size fields are ignored. It would be best to hide those fields when the diff VHD type is selected, but I could not figure out how to do that. (I agree with your previous comment about the way the UI is handled in this project...)

Note: this is not related to this PR, but I experienced some corruption in a diff VHD while testing today. Further testing is required; I will do some this weekend.

### CODE REVIEW

**Comment by shermp** [comment]
Sorry for being late with seeing this, Github didn't send an email notification for some reason 😢 

Looks to be a great start. I think there needs to be some changes regarding how the geometry is handled, especially for creation. The VHD geometry calculation algorithm is slightly different from the PCem algorithm, so the VHD algorithm should be used for VHD images. 

We also need to decide how to handle large disks (over 30GB), as the PCem GUI (currently) doesn't allow sectors-per-track (spt) greater than 63, whereas VHD images don't support more than 65535 cylinders.

**Comment by sards3** [comment]
> The VHD geometry calculation algorithm is slightly different from the PCem algorithm, so the VHD algorithm should be used for VHD images.

My first thought is that is we are creating VHDs specifically for PCem, so shouldn't we use PCem's geometry calculations? But then again:

> We also need to decide how to handle large disks (over 30GB), as the PCem GUI (currently) doesn't allow sectors-per-track (spt) greater than 63, whereas VHD images don't support more than 65535 cylinders.

That's a good point. So here is my second thought: Since PCem and the VHD spec have different maximum values for cylinders and sectors per track, and they also use different formulas to calculate the geometry, why not keep them separate?  PCem already stores its geometry settings in the machine config files. On the VHD side, the geometry is not used for any IO operations; it is really only metadata. So we could do something like this when creating VHDs:

1.  The user sets the PCem-specific geometry values in the PCem GUI.
2.  When the user clicks OK, calculate the total size of the disk based on those geometry values.
3.  Calculate the VHD-specific geometry based on that total size.
4.  Create the VHD using the VHD-specific geometry settings.
5.  Save the PCem-specific geometry settings in the PCem config file.

When loading an existing VHD into PCem, we can calculate the PCem-style geometry based on the total size of the VHD and store it in the PCem machine config, while leaving the VHD's internal geometry metadata untouched.

This could solve the issues you mentioned, but it does have the downside of there being a mismatch between the PCem geometry settings and the internal VHD geometry settings.  I think it would be worth it though. The internal VHD geometry settings are not going to have any practical effect from an end-user's perspective, and nobody is even going to know the difference unless they go poking around in the VHD file with a hex editor for some reason...

Let me know what you think.

**Comment by shermp** [comment]
I looked converting between PCem style and VHD style CHS for large disks, and it's not as simple as it might at first appear. This is because there is not a clean conversion possible between formats. One thought I had was when creating the VHD using the provided CHS settings in the GUI, we try and calculate the closet compatible CHS that works for both schemes and use that. It's really only a concern for large disks, so I doubt users will care if their provided CHS doesn't end up being the exact settings used.

To be honest, for smaller disks, the PCem calculation can probably be used. I think they only differ for really tiny disks. My main concern is that the total number of sectors, and the calculated size from that, should always match between PCem and VHD. 

EDIT: and the VHD format itself doesn't really care what CHS algorithm is used. I think the provided algorithm in the specs is one that's guaranteed to work with the old MS Virtual PC BIOS, but other than that, I don't think it matters.

**Comment by sards3** [comment]
> One thought I had was when creating the VHD using the provided CHS settings in the GUI, we try and calculate the closet compatible CHS that works for both schemes and use that.

But like you said, for large files, the schemes are not compatible, so I'm not sure how that would work. Perhaps I am not understanding exactly what you have in mind.

> My main concern is that the total number of sectors, and the calculated size from that, should always match between PCem and VHD.

We could just create the VHD with the exact requested amount of sectors, and set the internal VHD geometry as close as we can. This would require a minor change to MiniVHD to allow creation from a sector count as opposed to a geometry. After all, the max VHD size is 2040 GB, which is way more than the max CHS geometry, so it would be good to have that option anyway.  I just tested and Windows happily mounts a 1GB VHD with CHS of 0, 0, 0, so it clearly doesn't care about the geometry, but that might not be the case with other software.

Here is another possibility I just thought of:

1. The user sets the PCem-specific geometry values in the PCem GUI.
2. When the user clicks OK, calculate the total size of the disk based on those geometry values.
3. Calculate the VHD-specific geometry (using the VHD-spec algorithm) based on the total size from step 2.
4. If the geometry from step 3 results in a total size equal to the total size from step 2, go to step 6.
5. Else if the geometry from step 3 results in a total size that is smaller than the total size from step 2, increase the geometry so that the total size is >= the total size from step 2.
6. Create the VHD using the VHD-specific geometry settings.
7. Save the PCem-specific geometry settings in the PCem config file.

The result is a VHD that is equal or greater in size to the one requested in PCem, but never smaller. There may be a few extra wasted sectors at the end of the file, but it wouldn't be a problem.

Sorry for writing so much; I'm just brainstorming here.

**Comment by shermp** [comment]
> But like you said, for large files, the schemes are not compatible, so I'm not sure how that would work. Perhaps I am not understanding exactly what you have in mind.

Note that for large disks, I'm pretty sure CHS doesn't really matter, as I think at those sizes, LBA is what's actually used by BIOS/OS anyway.

The idea is to find the closest size to the desired size that satisfies both `c x 16 x 63` and `c x 16 x 255`. Then store the `c x 16 x 255` geometry to the VHD, and set the `c x 16 x 63` geometry in PCem. I did the maths to determine this once upon at time, but can't remember what it is, although I think it was something like:

*For a given number of sectors, divide the number by both (16 x 255) and (16 x 63). If the result of both divisions is a whole number of cylinders, then the size is compatible with both schemes, otherwise they aren't. Repeat until you find a number of sectors that work.*

Sarah told me the main reason PCem does not support `spt > 63` is that most of the systems emulated by PCem don't work with that geometry, although I've found that the Award socket 7 system (and probably later ones) does seem to work.

Also note, that the limitation is only enforced in the GUI. It's possible to set `c x 16 x 255` in the config file, and have it work for the newest systems emulated by PCem.

**Comment by sards3** [comment]
I have added some more commits to this PR. I implemented the handling of geometry and large files that you have talked about previously. I also made some small improvements to the HD creation UI. Finally, I added the ability to select a large or small block size when creating dynamic or diff VHDs. In my testing, using small block size can result in significant reduction in the size of the VHD file.

Please let me know your thoughts.

**Comment by shermp** [comment]
Looking good.

Main thing I think needs to be looked at now is that when opening a VHD, we should probably get the geometry (with conversion if necessary) from the VHD directly, rather than using `check_hd_type`. Might avoid any potential mismatch (it should be alright as-is, but I'm not confident enough in my math to be absolutely certain...)

**Comment by sards3** [comment]
The latest commit implements what you talked about in the previous comment.

**Comment by shermp** [comment]
Thank you very much. Let's merge

**Comment by shermp** [comment]
Just a quick note that Sarah integrated this into PCem!

**Comment by sards3** [comment]
That's great! Thanks for creating MiniVHD!

**Pull request merged**
